version: "3.9"

services:
  backend:
    image: p1-backend:latest
    container_name: trading_backend
    ports:
      - "8080:8080"
    restart: always

  frontend:
    image: p1-frontend:latest
    container_name: trading_frontend
    ports:
      - "8501:8501"
    environment:
      - API_BASE_URL=http://backend:8080
    depends_on:
      - backend
    restart: always
